[environments]
  [environments.development]
    name = "recipe"
    namespace = "dev"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""

[environments.live]
    name = "recipe"
    namespace = "live"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = ""
    chart = ""
    set = ["service.type=LoadBalancer", "service.externalPort=80"]