[environments]
  [environments.development]
    name = "shorturl"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
    set = ["os"="linux"] # TODO add var to chart to set `beta.kubernetes.io/os' constraint
  [environments.development.windows]
    name = "shorturl"
    namespace = "default"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile.windows"
    chart = ""
    set = ["os"="windows"] # TODO add var to chart to set `beta.kubernetes.io/os' constraint